INSERT INTO PLANTS (NAME, QUANTITY, WATERING_FREQUENCY, HAS_FRUIT, ACCESS_PASSWORD) VALUES ('Yucca', 5, 7, true, '123');
INSERT INTO PLANTS (NAME, QUANTITY, WATERING_FREQUENCY, HAS_FRUIT, ACCESS_PASSWORD) VALUES ('Calla Lily', 16, 4, false, '456');
INSERT INTO PLANTS (NAME, QUANTITY, WATERING_FREQUENCY, HAS_FRUIT, ACCESS_PASSWORD) VALUES ('Cherry Tree', 2, 3, false, '789');