INSERT INTO PLANTS (NAME, QUANTITY, WATERING_FREQUENCY, HAS_FRUIT) VALUES ('Banana Yucca', 5, 7, true);
INSERT INTO PLANTS (NAME, QUANTITY, WATERING_FREQUENCY, HAS_FRUIT) VALUES ('Calla Lily', 16, 4, false);
INSERT INTO PLANTS (NAME, QUANTITY, WATERING_FREQUENCY, HAS_FRUIT) VALUES ('Cherry Tree', 2, 3, false);